version: '3.8'

services:
  mqtt_broker:
    build: ./mqtt_broker
    networks:
      network_1:
        ipv4_address: 172.16.1.2
    ports:
      # The MQTT port
      - "1883:1883"
      # The port of the dashboard
      - "18083:18083"

  openhab_app:
    build: ./openhab_app
    networks:
      network_1:
        ipv4_address: 172.16.1.3
    ports:
      # The HTTP port of the web interface
      - "18080:8080"
      # The HTTPS port of the web interface
      - "18443:18443"
      # The SSH port of the Console
      - "18101:8101"
      # The LSP port for validating rules
      - "15007:5007"

  # web_app:
  #   build:
  #     context: ./web_app
  #     dockerfile: Dockerfile.prod
  #   networks:
  #     network_1:
  #       ipv4_address: 172.16.1.4
  #   command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
  #   volumes:
  #     - static_volume:/home/app/web/staticfiles
  #     - media_volume:/home/app/web/mediafiles
  #   expose:
  #     - 8000
  #   env_file:
  #     - ./.env.prod
  #   depends_on:
  #     - db

  # db:
  #   image: postgres:12.3-alpine
  #   networks:
  #     network_1:
  #       ipv4_address: 172.16.1.5
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   env_file:
  #     - ./.env.prod.db

  # nginx:
  #   build: ./nginx
  #   networks:
  #     network_1:
  #       ipv4_address: 172.16.1.6
  #   volumes:
  #     - static_volume:/home/app/web/staticfiles
  #     - media_volume:/home/app/web/mediafiles
  #   ports:
  #     - 1337:80
  #   depends_on:
  #     - web_app

# volumes:
#   postgres_data:
#   static_volume:
#   media_volume:

# networks:
#   network_1:
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.16.1.0/24
#         gateway: 172.16.1.1

